version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=the_syndicate_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:6-alpine

  migrate:
    build: .
    command: python manage.py migrate --no-input
    environment:
      - DJANGO_SECRET_KEY=it-does-not-matter-for-migrations
      - DEBUG=0
      - DATABASE_URL=postgres://user:password@db:5432/the_syndicate_db
    depends_on:
      - db

  web:
    build: .
    command: gunicorn the_syndicate.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=a-real-secret-key-for-the-love-of-god
      - DEBUG=1
      - DATABASE_URL=postgres://user:password@db:5432/the_syndicate_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
    depends_on:
      - migrate
      - redis

  celery_worker:
    build: .
    command: celery -A the_syndicate worker -l info
    environment:
      - DJANGO_SECRET_KEY=a-real-secret-key-for-the-love-of-god
      - DEBUG=1
      - DATABASE_URL=postgres://user:password@db:5432/the_syndicate_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - migrate
      - redis

  celery_beat:
    build: .
    command: celery -A the_syndicate beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DJANGO_SECRET_KEY=a-real-secret-key-for-the-love-of-god
      - DEBUG=1
      - DATABASE_URL=postgres://user:password@db:5432/the_syndicate_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - migrate
      - redis

volumes:
  db_data: